language: csharp
solution: DesafioExtratosMSA.sln
mono: none
dotnet: 2.1.801
install:
script:
  - dotnet restore
  - dotnet build
  - cd tools
  - dotnet restore
  - dotnet minicover instrument --workdir ../ --assemblies src/Services/Establishments/Establishments.Tests/**/bin/**/*.dll --sources src/Services/Establishments/Establishments.API/Controllers/**/*.cs
  - dotnet minicover instrument --workdir ../ --assemblies src/Services/Releases/Releases.Tests/**/bin/**/*.dll --sources src/Services/Releases/Releases.API/Controllers/**/*.cs
  - dotnet minicover instrument --workdir ../ --assemblies src/Services/Statements/Statements.Tests/**/bin/**/*.dll --sources src/Services/Statements/Statements.API/Controllers/**/*.cs
  - dotnet minicover reset
  - cd ..
  - dotnet test --no-build ./src/Services/Establishments/Establishments.Tests/Establishments.Tests.csproj --verbosity normal
  - dotnet test --no-build ./src/Services/Releases/Releases.Tests/Releases.Tests.csproj --verbosity normal
  - dotnet test --no-build ./src/Services/Statements/Statements.Tests/Statements.Tests.csproj --verbosity normal
  - cd tools
  - dotnet minicover uninstrument --workdir ../
  - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"